// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PenProtocol.proto

package edu.ucsd.hci.interactivespace.annotopen.protobuf;

public final class AnnotoPenProtocol {
  private AnnotoPenProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    CustomString(0, 0),
    CustomBytes(1, 1),
    Status(2, 2),
    Motion(3, 3),
    ;
    
    public static final int CustomString_VALUE = 0;
    public static final int CustomBytes_VALUE = 1;
    public static final int Status_VALUE = 2;
    public static final int Motion_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return CustomString;
        case 1: return CustomBytes;
        case 2: return Status;
        case 3: return Motion;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      CustomString, CustomBytes, Status, Motion, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:InteractiveSpace.MessageType)
  }
  
  public enum StatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    Connected(0, 0),
    Starting(1, 1),
    Ready(2, 2),
    Error(3, 3),
    ;
    
    public static final int Connected_VALUE = 0;
    public static final int Starting_VALUE = 1;
    public static final int Ready_VALUE = 2;
    public static final int Error_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static StatusCode valueOf(int value) {
      switch (value) {
        case 0: return Connected;
        case 1: return Starting;
        case 2: return Ready;
        case 3: return Error;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final StatusCode[] VALUES = {
      Connected, Starting, Ready, Error, 
    };
    
    public static StatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private StatusCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:InteractiveSpace.StatusCode)
  }
  
  public enum MotionCode
      implements com.google.protobuf.ProtocolMessageEnum {
    PenDown(0, 0),
    PenUp(1, 1),
    PenMove(2, 2),
    ;
    
    public static final int PenDown_VALUE = 0;
    public static final int PenUp_VALUE = 1;
    public static final int PenMove_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static MotionCode valueOf(int value) {
      switch (value) {
        case 0: return PenDown;
        case 1: return PenUp;
        case 2: return PenMove;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MotionCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MotionCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MotionCode>() {
            public MotionCode findValueByNumber(int number) {
              return MotionCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final MotionCode[] VALUES = {
      PenDown, PenUp, PenMove, 
    };
    
    public static MotionCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MotionCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:InteractiveSpace.MotionCode)
  }
  
  public interface StatusMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .InteractiveSpace.StatusCode status = 1;
    boolean hasStatus();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode getStatus();
    
    // optional string message = 2;
    boolean hasMessage();
    String getMessage();
  }
  public static final class StatusMessage extends
      com.google.protobuf.GeneratedMessage
      implements StatusMessageOrBuilder {
    // Use StatusMessage.newBuilder() to construct.
    private StatusMessage(Builder builder) {
      super(builder);
    }
    private StatusMessage(boolean noInit) {}
    
    private static final StatusMessage defaultInstance;
    public static StatusMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_StatusMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_StatusMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .InteractiveSpace.StatusCode status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode getStatus() {
      return status_;
    }
    
    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode.Connected;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_StatusMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_StatusMessage_fieldAccessorTable;
      }
      
      // Construct using edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode.Connected;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDescriptor();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage getDefaultInstanceForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage build() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage buildPartial() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage result = new edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage) {
          return mergeFrom((edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage other) {
        if (other == edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode value = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .InteractiveSpace.StatusCode status = 1;
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode.Connected;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode getStatus() {
        return status_;
      }
      public Builder setStatus(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusCode.Connected;
        onChanged();
        return this;
      }
      
      // optional string message = 2;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:InteractiveSpace.StatusMessage)
    }
    
    static {
      defaultInstance = new StatusMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:InteractiveSpace.StatusMessage)
  }
  
  public interface MotionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .InteractiveSpace.MotionCode motion = 1;
    boolean hasMotion();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode getMotion();
    
    // optional float x = 2;
    boolean hasX();
    float getX();
    
    // optional float y = 3;
    boolean hasY();
    float getY();
  }
  public static final class MotionMessage extends
      com.google.protobuf.GeneratedMessage
      implements MotionMessageOrBuilder {
    // Use MotionMessage.newBuilder() to construct.
    private MotionMessage(Builder builder) {
      super(builder);
    }
    private MotionMessage(boolean noInit) {}
    
    private static final MotionMessage defaultInstance;
    public static MotionMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public MotionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_MotionMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_MotionMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .InteractiveSpace.MotionCode motion = 1;
    public static final int MOTION_FIELD_NUMBER = 1;
    private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode motion_;
    public boolean hasMotion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode getMotion() {
      return motion_;
    }
    
    // optional float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getX() {
      return x_;
    }
    
    // optional float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getY() {
      return y_;
    }
    
    private void initFields() {
      motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode.PenDown;
      x_ = 0F;
      y_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMotion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, motion_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, motion_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_MotionMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_MotionMessage_fieldAccessorTable;
      }
      
      // Construct using edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode.PenDown;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDescriptor();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage getDefaultInstanceForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage build() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage buildPartial() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage result = new edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.motion_ = motion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage) {
          return mergeFrom((edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage other) {
        if (other == edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance()) return this;
        if (other.hasMotion()) {
          setMotion(other.getMotion());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMotion()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode value = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                motion_ = value;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .InteractiveSpace.MotionCode motion = 1;
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode.PenDown;
      public boolean hasMotion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode getMotion() {
        return motion_;
      }
      public Builder setMotion(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        motion_ = value;
        onChanged();
        return this;
      }
      public Builder clearMotion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionCode.PenDown;
        onChanged();
        return this;
      }
      
      // optional float x = 2;
      private float x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getX() {
        return x_;
      }
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float y = 3;
      private float y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getY() {
        return y_;
      }
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:InteractiveSpace.MotionMessage)
    }
    
    static {
      defaultInstance = new MotionMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:InteractiveSpace.MotionMessage)
  }
  
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .InteractiveSpace.MessageType type = 1;
    boolean hasType();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType getType();
    
    // optional uint32 time = 2;
    boolean hasTime();
    int getTime();
    
    // optional string customString = 3;
    boolean hasCustomString();
    String getCustomString();
    
    // optional bytes customBytes = 4;
    boolean hasCustomBytes();
    com.google.protobuf.ByteString getCustomBytes();
    
    // optional .InteractiveSpace.StatusMessage status = 5;
    boolean hasStatus();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage getStatus();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder getStatusOrBuilder();
    
    // optional .InteractiveSpace.MotionMessage motion = 6;
    boolean hasMotion();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage getMotion();
    edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder getMotionOrBuilder();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .InteractiveSpace.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType getType() {
      return type_;
    }
    
    // optional uint32 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTime() {
      return time_;
    }
    
    // optional string customString = 3;
    public static final int CUSTOMSTRING_FIELD_NUMBER = 3;
    private java.lang.Object customString_;
    public boolean hasCustomString() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCustomString() {
      java.lang.Object ref = customString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          customString_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCustomStringBytes() {
      java.lang.Object ref = customString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        customString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes customBytes = 4;
    public static final int CUSTOMBYTES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString customBytes_;
    public boolean hasCustomBytes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getCustomBytes() {
      return customBytes_;
    }
    
    // optional .InteractiveSpace.StatusMessage status = 5;
    public static final int STATUS_FIELD_NUMBER = 5;
    private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage getStatus() {
      return status_;
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder getStatusOrBuilder() {
      return status_;
    }
    
    // optional .InteractiveSpace.MotionMessage motion = 6;
    public static final int MOTION_FIELD_NUMBER = 6;
    private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage motion_;
    public boolean hasMotion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage getMotion() {
      return motion_;
    }
    public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder getMotionOrBuilder() {
      return motion_;
    }
    
    private void initFields() {
      type_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType.CustomString;
      time_ = 0;
      customString_ = "";
      customBytes_ = com.google.protobuf.ByteString.EMPTY;
      status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance();
      motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasStatus()) {
        if (!getStatus().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMotion()) {
        if (!getMotion().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCustomStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, customBytes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, motion_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCustomStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, customBytes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, motion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.internal_static_InteractiveSpace_Message_fieldAccessorTable;
      }
      
      // Construct using edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
          getMotionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType.CustomString;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        customString_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        customBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (statusBuilder_ == null) {
          status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (motionBuilder_ == null) {
          motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance();
        } else {
          motionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.getDescriptor();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message getDefaultInstanceForType() {
        return edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.getDefaultInstance();
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message build() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message buildPartial() {
        edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message result = new edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.customString_ = customString_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.customBytes_ = customBytes_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (motionBuilder_ == null) {
          result.motion_ = motion_;
        } else {
          result.motion_ = motionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message) {
          return mergeFrom((edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message other) {
        if (other == edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasCustomString()) {
          setCustomString(other.getCustomString());
        }
        if (other.hasCustomBytes()) {
          setCustomBytes(other.getCustomBytes());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasMotion()) {
          mergeMotion(other.getMotion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasStatus()) {
          if (!getStatus().isInitialized()) {
            
            return false;
          }
        }
        if (hasMotion()) {
          if (!getMotion().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType value = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              customString_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              customBytes_ = input.readBytes();
              break;
            }
            case 42: {
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder subBuilder = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.newBuilder();
              if (hasStatus()) {
                subBuilder.mergeFrom(getStatus());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStatus(subBuilder.buildPartial());
              break;
            }
            case 50: {
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder subBuilder = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.newBuilder();
              if (hasMotion()) {
                subBuilder.mergeFrom(getMotion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMotion(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .InteractiveSpace.MessageType type = 1;
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType type_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType.CustomString;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType getType() {
        return type_;
      }
      public Builder setType(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MessageType.CustomString;
        onChanged();
        return this;
      }
      
      // optional uint32 time = 2;
      private int time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTime() {
        return time_;
      }
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }
      
      // optional string customString = 3;
      private java.lang.Object customString_ = "";
      public boolean hasCustomString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCustomString() {
        java.lang.Object ref = customString_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          customString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCustomString(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        customString_ = value;
        onChanged();
        return this;
      }
      public Builder clearCustomString() {
        bitField0_ = (bitField0_ & ~0x00000004);
        customString_ = getDefaultInstance().getCustomString();
        onChanged();
        return this;
      }
      void setCustomString(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        customString_ = value;
        onChanged();
      }
      
      // optional bytes customBytes = 4;
      private com.google.protobuf.ByteString customBytes_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasCustomBytes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getCustomBytes() {
        return customBytes_;
      }
      public Builder setCustomBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        customBytes_ = value;
        onChanged();
        return this;
      }
      public Builder clearCustomBytes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        customBytes_ = getDefaultInstance().getCustomBytes();
        onChanged();
        return this;
      }
      
      // optional .InteractiveSpace.StatusMessage status = 5;
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder> statusBuilder_;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      public Builder setStatus(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setStatus(
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeStatus(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              status_ != edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance()) {
            status_ =
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder getStatusBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessageOrBuilder>(
                  status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      
      // optional .InteractiveSpace.MotionMessage motion = 6;
      private edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder> motionBuilder_;
      public boolean hasMotion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage getMotion() {
        if (motionBuilder_ == null) {
          return motion_;
        } else {
          return motionBuilder_.getMessage();
        }
      }
      public Builder setMotion(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage value) {
        if (motionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          motion_ = value;
          onChanged();
        } else {
          motionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setMotion(
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder builderForValue) {
        if (motionBuilder_ == null) {
          motion_ = builderForValue.build();
          onChanged();
        } else {
          motionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeMotion(edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage value) {
        if (motionBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              motion_ != edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance()) {
            motion_ =
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.newBuilder(motion_).mergeFrom(value).buildPartial();
          } else {
            motion_ = value;
          }
          onChanged();
        } else {
          motionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearMotion() {
        if (motionBuilder_ == null) {
          motion_ = edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.getDefaultInstance();
          onChanged();
        } else {
          motionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder getMotionBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getMotionFieldBuilder().getBuilder();
      }
      public edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder getMotionOrBuilder() {
        if (motionBuilder_ != null) {
          return motionBuilder_.getMessageOrBuilder();
        } else {
          return motion_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder> 
          getMotionFieldBuilder() {
        if (motionBuilder_ == null) {
          motionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder, edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessageOrBuilder>(
                  motion_,
                  getParentForChildren(),
                  isClean());
          motion_ = null;
        }
        return motionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:InteractiveSpace.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:InteractiveSpace.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InteractiveSpace_StatusMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InteractiveSpace_StatusMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InteractiveSpace_MotionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InteractiveSpace_MotionMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InteractiveSpace_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InteractiveSpace_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PenProtocol.proto\022\020InteractiveSpace\"N\n" +
      "\rStatusMessage\022,\n\006status\030\001 \002(\0162\034.Interac" +
      "tiveSpace.StatusCode\022\017\n\007message\030\002 \001(\t\"S\n" +
      "\rMotionMessage\022,\n\006motion\030\001 \002(\0162\034.Interac" +
      "tiveSpace.MotionCode\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001" +
      "(\002\"\321\001\n\007Message\022+\n\004type\030\001 \002(\0162\035.Interacti" +
      "veSpace.MessageType\022\014\n\004time\030\002 \001(\r\022\024\n\014cus" +
      "tomString\030\003 \001(\t\022\023\n\013customBytes\030\004 \001(\014\022/\n\006" +
      "status\030\005 \001(\0132\037.InteractiveSpace.StatusMe" +
      "ssage\022/\n\006motion\030\006 \001(\0132\037.InteractiveSpace",
      ".MotionMessage*H\n\013MessageType\022\020\n\014CustomS" +
      "tring\020\000\022\017\n\013CustomBytes\020\001\022\n\n\006Status\020\002\022\n\n\006" +
      "Motion\020\003*?\n\nStatusCode\022\r\n\tConnected\020\000\022\014\n" +
      "\010Starting\020\001\022\t\n\005Ready\020\002\022\t\n\005Error\020\003*1\n\nMot" +
      "ionCode\022\013\n\007PenDown\020\000\022\t\n\005PenUp\020\001\022\013\n\007PenMo" +
      "ve\020\002BE\n0edu.ucsd.hci.interactivespace.an" +
      "notopen.protobufB\021AnnotoPenProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InteractiveSpace_StatusMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InteractiveSpace_StatusMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InteractiveSpace_StatusMessage_descriptor,
              new java.lang.String[] { "Status", "Message", },
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.class,
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.StatusMessage.Builder.class);
          internal_static_InteractiveSpace_MotionMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_InteractiveSpace_MotionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InteractiveSpace_MotionMessage_descriptor,
              new java.lang.String[] { "Motion", "X", "Y", },
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.class,
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.MotionMessage.Builder.class);
          internal_static_InteractiveSpace_Message_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_InteractiveSpace_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InteractiveSpace_Message_descriptor,
              new java.lang.String[] { "Type", "Time", "CustomString", "CustomBytes", "Status", "Motion", },
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.class,
              edu.ucsd.hci.interactivespace.annotopen.protobuf.AnnotoPenProtocol.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
